<template>
  <article class="max-w-2xl mx-auto">
    <h1 class="text-2xl font-bold text-white mb-1">Terms of Service</h1>
    <p class="text-sm text-gray-500 mb-8">Last updated {{ updated }}</p>

    <section v-for="s in sections" :key="s.title" class="mb-7">
      <h2 class="text-base font-semibold text-white mb-2">{{ s.title }}</h2>
      <p v-for="(p, i) in s.body" :key="i" class="text-sm text-gray-300 leading-relaxed mb-2">
        <span v-html="p" />
      </p>
      <ul v-if="s.list" class="mt-2 space-y-1.5">
        <li v-for="l in s.list" :key="l" class="text-sm text-gray-400 flex gap-2">
          <span class="text-gray-600 shrink-0">•</span><span v-html="l" />
        </li>
      </ul>
    </section>

    <p class="text-xs text-gray-600 border-t border-gray-800 pt-4">
      Contact: <a :href="`mailto:${contact}`" class="text-blue-400 hover:text-blue-300">{{ contact }}</a>
    </p>
  </article>
</template>

<script setup lang="ts">
const contact = 'ranajoy121@gmail.com'
const updated = '30 August 2026'

const sections = [
  {
    title: 'What this is',
    body: [
      'A personal tool for tracking a portfolio and reading publicly available company data. It is offered free of charge, as-is, with no guarantee that it will keep working or keep existing.',
    ],
  },
  {
    title: 'This is not financial advice',
    body: [
      'Nothing in this application is advice, a recommendation, or an offer to buy or sell any security or asset. It presents data and machine-written summaries of published articles. Investment decisions are yours alone, and you are responsible for their outcome.',
    ],
  },
  {
    title: 'The data can be wrong',
    body: [
      'Figures come from third parties and from public regulatory filings, and are reproduced without independent verification. In particular:',
    ],
    list: [
      'Prices may be delayed, stale outside market hours, or simply incorrect.',
      'Some quarterly figures are <em>derived</em> — where a company reports only an annual total, the fourth quarter is calculated by subtraction. These are labelled as derived.',
      'Written summaries are generated by a language model. It can misread, omit, or overstate. Source articles are linked so you can check.',
      'Company coverage is limited to S&P 500 members; anything else may have no data at all.',
    ],
  },
  {
    title: 'Your account',
    body: [
      'You are responsible for keeping your credentials secure and for the accuracy of what you enter. One person, one account. Do not use the service to break the law, to attack the infrastructure, or to scrape it at volume.',
    ],
  },
  {
    title: 'Availability',
    body: [
      'The service runs on free hosting tiers. It sleeps when idle, may be slow to wake, and can be unavailable without notice. There is no uptime commitment and no support obligation.',
    ],
  },
  {
    title: 'Ending it',
    body: [
      'You can delete your account at any time from the Account page, which removes your data immediately. The service may be discontinued or accounts closed at any time, though reasonable effort will be made to give notice first.',
    ],
  },
  {
    title: 'Liability',
    body: [
      'To the fullest extent the law allows, no liability is accepted for any loss arising from use of this application — including investment losses, lost data, or lost profit. Nothing here excludes liability that cannot lawfully be excluded.',
    ],
  },
  {
    title: 'Governing law',
    body: [
      'These terms are governed by German law, and mandatory consumer protections in your country of residence continue to apply.',
    ],
  },
]

useHead({ title: 'Terms of Service · Portfolio Tracker' })
</script>
